services:
  minidoc:
    build: .
    container_name: minidoc
    image: minidoc:latest
    ports:
      - '5001:5001'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    
    volumes:
      - .:/minidoc
    env_file:
      - .env  

      